### PR TITLE
Rework zpool's basic management (pool creation, expansion & destruction)

### LINKED ISSUE #50: Object deletion does not work properly on NVMe drives when using by-id dev alias
Tested using:
* ``openmediavault``: 4.1.11
* ``openmediavault-zfs``: 4.0.4

It appears that the OMV-ZFS plugin does not properly support NVMe drives when deleting objects from pools created on these drives when using "by-id" dev aliasing. By analysing how ``OMVModuleZFSZpool::getDevDisks`` works, it appears that anything that uses this method (currently, limited to object deletion) won't work properly with these drives, because of a wrong assumption (that drives exist only as ``/dev/sdXY`` devices, where ``X`` is the drives letter and ``Y`` is its partition).

Consider the following scenario:
1. Create a zpool using an NVMe drive (a basic pool is fine for this demonstration) and "by-id" aliasing
2. The pool is created properly, no problems here
3. Try to delete the pool
4. When deleting, an error occurs with this message:
    > Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zpool labelclear /dev/nvme0n11 2>&1' with exit code '1': failed to open /dev/nvme0n11: No such file or directory

As you can see above, plugin is trying to clear the label on ``/dev/nvme0n11`` device, which does not exist (because that not how Linux creates NVMe drives' entries, so far I've seen something like this when dealing with partitions: ``/dev/nvme0n1p1``). The extraneous ``1`` at the end is appended by ``OMVModuleZFSZpool::getDevDisks``, which appears to do that either when dealing with "by-id" aliases or "by-path" aliases.

To be fair, it appears that this is not entirely plugins fault, as I've been able to find a similar problem in zfsOnLinux's repo here: https://github.com/zfsonlinux/zfs/issues/3478 - looks like pool creation does not properly partition CCISS (and NVMe as reported at the end) drives.

However, even if this issue gets eventually fixed, plugin's ``::getDevDisks`` method is still wrong - it should use ``nvme<disk_no>p<partition_number>`` scheme for NVMe drives, not the ``sd<disk_letter><partition_number>`` that occurs with regular SATA drives.

This problem (in conjunction with very limited "by-id" regexp capabilities) will also occur when using zpools on encrypted drives (eg. using LUKS).

### PR DESCRIPTION
**Pull request by mdziekon**
This Pull Request reworks the two most basic operations performed on a zpool - its creation, and its destruction. Most of the works was done on the "low-level", by adding a new, more powerful parser of the ``zpool status`` command, which allowed to fix some issues with certain types of drives not being properly cleared of the ZFS label. It should also be really useful in the future, as it easily reads **all** informations about devices added to the pool, preserving their hierarchy, states & statistics.

Some background:
---

There was a discussion on OMV's forum about some problems related to creation of Zpools on LUKS-encrypted devices (relevant part starts around here: https://forum.openmediavault.org/index.php/Thread/24456-ZFS-Mirror-Pool-creation-fails-on-LUKS-encrypted-devices/?postID=185301#post185301). The original problem was caused by the fact that ZFS plugin tries to create GPT labels for each device before creating the pool itself (but that was it, no new partitions were actually created on the device). This lead to a situation where a previously decrypted LUKS device would get the GPT label, but then, when zpool's creation has started, it would lead to an error and automatic re-encryption of the device. The most likely cause is that ZOL will partition the device if it thinks it's necessary, but since the plugin actually did **not** create any partitions, they both collide somehow creating a problem.

Since ZOL can handle the partitioning itself, it looks like the pre-labeling step is unnecessary and can be delegated to ZOL.

There's was the problem of incorrect ZFS labels removal at pool's destruction. This problem is related to plugin's devices retrieving method - it's pretty old and does not handle more exotic devices like NVMe drives (see https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/issues/50) or DeviceMapper devices (see https://forum.openmediavault.org/index.php/Thread/24456-ZFS-Mirror-Pool-creation-fails-on-LUKS-encrypted-devices/?postID=185288#post185288). First of all - it always assumes that the device is partitioned (which might not be true); second - it assumes the ``sd<device_letter><partition_no>`` partitioning scheme (eg. for NVMe drives it will be eg. ``nvme0n<device_letter>p<partition_no>``). Both of these assumptions basically restrict us to SATA devices only, otherwise pool's deletion will always fail and the labels will have to be cleared manually (or the device wiped completely). On top of that, the previous implementation completely ignored SLOGs, Caches & Spares (the plugin does not handle them properly anyway, but you can still add them manually).

What was done in this Pull Request:
---

The main part of this PR is... the pool's status parser. The pool's creation bugfix is a very simple change, in total only 6 removed lines. The pool's destruction however required to change how we're enumerating all devices added to the pool, to make it more flexible. I'm aware that this looks like a huge overkill (after all, I could simply fix the previous implementation with additional special cases), but I still think it was worth it if we consider that the plugin needs a make-over. This piece should be seen as the first step of that make-over - now we have a pretty good mechanism of dealing with basic informations about the pool. With this parser, the rest of the plugin should easily understand the hierarchy of a pool and be able to manage its special vdevs more easily (eg. adding/removing logs or caches on demand, or even enumerating them without using that ugly "SHOW ALL THE DETAILS" modal).

There's another new thing in this PR: **tests**. Since the status displaying command is internally pretty complicates (as in - it has many different cases to handle in a parser), I've made the effort to at least partially ensure that we're parsing it correctly, and further changes will be less likely to accidentally break something. Overall, I've added ~60 tests, most of them related to the parsing itself (with multiple different scenarios tested). But... please note that I originally come from a different environment, where tests are written in a different way. I've never worked with PHPUnit before, and I'm not sure if my approach is actually correct. However, if that's an acceptable solution, I had a plan to maybe setup a Travis configuration for this repo (again, never done this before, I'm more of a Gitlab CI guy, but at a first glance it looks rather simple to do something similar with Travis), we'll see how this goes.

Other things to note / discuss:
---

- I have no idea what's the "OpenMediaVault Plugin Developers" standpoint on all licensing stuff. OMV has a strict set of rules about that stuff, however I was not able to find anything like this for plugin developers. In addition to that, it seems that licensing in this plugin is already a mess (as in - certain files have no licensing information at all, others have the original author credited, and some have what seems to be the "OMV-like" licensing header). If that needs to be changed, please provide me with some comments on what should be done (well, that's the point of Code Review anyway...)
- I admit that I'm a bit rusty in terms of using PHP (I do not work with it on a daily basis anymore), and I actually have never used PHP 7+. I don't know if this was a "revolution", or an "evolution" in terms of the language internals, so if my code looks outdated, please let me know.
- I did not remove the old ``assemblePool`` method because I didn't want to break other things that depend on its format. However, it should be noted that some of the zpool class methods are never used... 
- ~**Please consider this Pull Request as "Still work in progress"** - **the code is done**, but I feel like I still need a day or two to verify if there are no obvious mistakes, either in the code, or in tests (especially in testcases, even though I've used outputs generated on a VM and a real machine, some parts are still manually crafted, like device names, so I want to confirm that my mocks are not broken because of a typo or something like that). What I'm trying to say here - I consider my "coding" work done, so it's ready for review, but I still might want to push a commit or two even before someone starts their review.~  
  **Update 2018-10-21:** I've finished my own final code review. This PR should now be considered as **COMPLETED** (at least until someone does an actual code review and leaves comments for me to fix or change something)

Closes #50

### CODE REVIEW

**Comment by subzero79** [comment]
Just did a quick try on my testing VM seems ok, 

the correction of destroying a pool your're going to submit it in a separate PR?

can ask @votdev about the test units.

**Comment by mdziekon** [comment]
@subzero79 
> can ask @votdev about the test units.

The thing is, these tests are already loosely based on the OMV's repo tests, which to my surprise, don't have that many tests anyway. While I took a different approach with mocks & expectations loading (external files rather than inline code, mostly because these mocks & expectations are pretty long, so I didn't want to pollute the tests themselves with the data too much), I think the rest is more or less similar.

I mean, obviously any constructive criticism is more than welcome here, but looking at what there already is in OMV's repo, I think @votdev won't be able to help us that much.

**Comment by subzero79** [comment]
I’ll test again. Because I got the same error as the backend attempts to clear the labels on dm-11 and dm-21 when using device mapper (crypto devices).

**Comment by mdziekon** [comment]
> I’ll test again. Because I got the same error as the backend attempts to clear the labels on dm-11 and dm-21 when using device mapper (crypto devices).

Please retest. Personally, I was able to successfully remove a pool with a mirror using two crypto devices. If it's still reproducible, please provide exact "steps to reproduce" so I can try to do the same thing and see if I've missed some edge case.

**Comment by mdziekon** [comment]
Ok, at this point I think I have nothing else to add or change in this PR, so please consider it to be **COMPLETED** (at least until someone does an actual code review and leaves comments for me to fix or change something) and **READY FOR CODE REVIEW**.

Changes since the PR creation date:
* Removed unnecessary ``LC_ALL`` env when calling ``zpool status`` (OMV takes care of translations already using ``LANG=C`` export)
* Improved documentation of parsing methods
* Added one more test case for the parser (checking if "errors counters" parsing works fine)
* Minor general cleanups:
    * Added ``.editorconfig`` based on current formatting of the project's files
    * Added ``composer.json`` file to include phpunit in dev builds
    * Updated README to markdown
    * PHP testing is now handled via composer's script
* Added Travis CI configuration file which runs PHP tests automatically.  
  @ryecoaaron to enable CI for this repo, please [this README file](https://github.com/travis-ci-examples/php-example/blob/master/README.md).  
  However, if you do not consider enabling it at all, please let me know so I can remove it from the repo (no point in having it if it won't be used).

---

Also, a note about the whole parser thing - as an alternative to ``zpool status``, it is also possible to fetch some informations about a pool using ``zdb`` command. However, even though it has many options, it seems it does not contain all the details (eg. it does not have any information about SLOGs, vdev statuses or vdev errors count). Maybe they will enhance that in the future, but for now it seems we're stuck with the ``status`` command, which is unfortunately not that "parser-friendly".

**Comment by ryecoaaron** [comment]
@mdziekon I will look into setting up the travis CI stuff in the next couple of days unless @subzero79 has a chance to do it before then.

**Comment by ryecoaaron** [comment]
@mdziekon I will look into setting up the travis CI stuff in the next couple of days unless @subzero79 has a chance to do it before then.

**Comment by subzero79** [comment]
I just pulled the updated PR, no errors this time removing the pool.

Once thing i did notice and i don't know when it got lost, must be the new storage implementation changes in core omv some time ago is the capability of formating zfs volumes (virtual block devices) in the omv filesystem section, once formatted in cli they appear. Is not critical for now. But it will be critical if one day the iscsi plugin gets revived.

**Comment by mdziekon** [comment]
@subzero79:
> Once thing i did notice and i don't know when it got lost, must be the new storage implementation changes in core omv some time ago is the capability of formating zfs volumes (virtual block devices) in the omv filesystem section, once formatted in cli they appear. Is not critical for now. But it will be critical if one day the iscsi plugin gets revived.

I haven't changed anything related to things other than pool creation and deletion, so I'm pretty sure it's not related to this PR (just like you said, most likely something that has been gone for a long time since the migration to newer version of OMV). So as long as it is not a regression (caused by this PR), we shouldn't bother with it here. You should raise a new issue here on Github, someone might want to take that up later.

**Comment by mdziekon** [comment]
Here, I've force-updated (no code changes) my latest commit. From now on, Travis will pick up commit hooks and automatically run tests in the background.

**Pull request merged**
